apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx-test
spec:
  rules:
  - host: www.zhangli07.com
    http:
      paths:
      - path: /
        backend:
          serviceName: myapp
          servicePort: 80
